### ISSUE TITLE
请教Lagrange.OneBot的配置问题

### ISSUE THREAD

**Issue by lepollo** [Linwenxuan05/Lagrange.Core#4]
1. 以下代码中output的参数是固定的，还是需要自己配置？
QrCodeHelper.Output("https://txz.qq.com/p?k=1GF4r45MPwoy6ZSJSuRdlwyKlKOleKyi&f=1600001615")

2. 以下代码中的appconfig.json需要配置哪些字段？
var hostBuilder = new LagrangeAppBuilder(args).ConfigureConfiguration("appsettings.json", false, true);

**Comment by Linwenxuan05** [comment]
Lagrange.OneBot暂不可用 对于OneBot11的支持还在咕咕咕 如果有需要的话可以等待后续更新或者PR
（优先级不会很高 因为作者本人是直接基于C#内核进行开发的）
里面的链接是测试二维码Console输出留下的Debug参数 可以忽略

**Comment by lepollo** [comment]
啊，你好快！谢谢解答
