### ISSUE TITLE
抛砖引玉：一个不成熟的bot启动示例

### ISSUE THREAD

**Issue by lepollo** [Linwenxuan05/Lagrange.Core#6]
说明：

1.启动示例：await LagrangeRunning.RunSync();
2._Utility.SaveJson方法很简单，自己写。
3.SaveDeviceInfo(BotDeviceInfo)和SaveKeyStore(bot.UpdateKeystore())放在online事件中不知道是否合理。
4.未解决问题：每次都要扫码登录（即使手机上已经勾选‘下次不扫码直接登录’） 

代码如下：
using Lagrange.Core;
using Lagrange.Core.Common;
using Lagrange.Core.Common.Interface;
using Lagrange.Core.Common.Interface.Api;
using MyUtility;
namespace Lagrange.Running

{
    public static class LagrangeRunning
    {
        static BotDeviceInfo BotDeviceInfo = LoadDeviceInfo();
        static BotContext bot = BotFactory.Create(new BotConfig(), BotDeviceInfo, LoadKeyStore());

        static LagrangeRunning()
        {
            BotInit();
        }
        static void BotInit()
        {
            bot.Invoker.OnBotLogEvent += (context, @event) =>
            {
                if (@event.ToString().Contains("Heartbeat.Alive") == false)
                    Console.WriteLine(@event.ToString());
            };

            bot.Invoker.OnBotOnlineEvent += (context, @event) =>
            {
                Console.WriteLine(@event.ToString());
                SaveDeviceInfo(BotDeviceInfo);
                SaveKeyStore(bot.UpdateKeystore());
            };
            bot.Invoker.OnGroupMessageReceived += (context, @event) =>
            {
                Console.WriteLine(@event.Chain.ToString());
            };
        }
        public static async Task RunSync()
        {
            var qrcode = bot.FetchQrCode().Result;
            if (qrcode == null) Console.WriteLine("Failed to fetch qrcode");
            else
            {
                File.WriteAllBytes("qrcode.png", qrcode);
                Console.WriteLine("请用手机QQ扫码登录：qrcode.png");
            }
            await bot.LoginByQrCode();
        }
        static BotDeviceInfo LoadDeviceInfo()
        {
            var deviceInfo = _Utility.LoadJson<BotDeviceInfo>("deviceinfo");
            if (deviceInfo != null) return deviceInfo;
            else return BotDeviceInfo.GenerateInfo();
        }

        static bool SaveDeviceInfo(BotDeviceInfo deviceInfo) => _Utility.SaveJson(deviceInfo, "deviceinfo");
        static BotKeystore LoadKeyStore()
        {
            var keyStore = _Utility.LoadJson<BotKeystore>("keystore");
            if (keyStore != null) return keyStore;
            else return new BotKeystore();
        }
        static bool SaveKeyStore(BotKeystore keyStore) => _Utility.SaveJson(keyStore, "keystore");

    }
}

**Comment by Linwenxuan05** [comment]
每次都要扫码登陆的原因是EasyLogin需要通过LoginByPassword来登录
正在考虑重构掉来把两个Login合二为一，并且通过EventInvoker来分发QrCode（现在这一个确实挺恶心的
你可以先修改一下 如果检测到了Keystore的存在即LoginByPassword
