### ISSUE TITLE
在获取 member.Permission 时返回错误的结果

### ISSUE THREAD

**Issue by NsCrosu** [Linwenxuan05/Lagrange.Core#7]
```c#
var member = bot.Fet`(ch)`Members((uint)group.Chain.GroupUin!).Result.First(x => x.Uin == memberUin);
var perm = member.Permission;
```
perm is "Member" when actual member role is Admin (most time)

**Comment by Linwenxuan05** [comment]
Closed as resolved in [#98](https://github.com/Linwenxuan05/Lagrange.Core/commit/b6c9b322e740bd48f7e99fa682fc8a2edaf6043c)
